ci: Add release and promote workflows
canonical/prometheus-juju-backup-all-exporter pull request #19
Opened 2024-05-03 13:02 UTC by dashmage

2024-05-03 13:03 UTC, dashmage commented
Note: `STORE_LOGIN` secret needs to be added.

2024-05-06 14:25 UTC, rgildein commented
Lint test are failing due issue with upload the PR_NUMBER artifact, however to overwrite is set true so it should not fail.

2024-05-06 16:46 UTC, aieri requested changes

2024-05-06 16:46 UTC, aieri commented on .github/workflows/promote.yaml
> +        run: echo "name=$(yq '.name' snap/snapcraft.yaml)" >> $GITHUB_OUTPUT
given how simple the parsing you want to do of `snapcraft.yaml` is, I'd suggest not including an extra dependency (especially after the xz mess...)

```suggestion
      - name: Snapcraft install
        run: sudo snap install --classic snapcraft
      - name: Get snap name
        id: snap
        run: grep -Po '(?<=^name:)\s*\K\w+' snap/snapcraft.yaml >> $GITHUB_OUTPUT
```

2024-05-06 19:25 UTC, zxhdaze submitted a review, later dismissed

2024-05-06 20:07 UTC, aieri submitted a review, later dismissed

2024-05-07 02:34 UTC, jneo8 submitted a review, later dismissed

2024-05-07 09:19 UTC, aieri approved these changes

2024-05-07 09:29 UTC, merged